character_start_params:
  max_health: 25
  health: 25
  strength: 6
  agility: 6

levels:
  - range: [1, 5]
    enemy_chances:
      zombie: 60
      ghost: 40
      vampire: 0
      snake_wizard: 0
      ogr: 0
    enemy_count: [2, 4]
    items_count: [15, 20]
    treasure: [80, 120]

  - range: [6, 10]
    enemy_chances:
      zombie: 30
      ghost: 30
      vampire: 20
      snake_wizard: 15
      ogr: 5
    enemy_count: [4, 6]
    items_count: [10, 15]
    treasure: [150, 250]

  - range: [11, 15]
    enemy_chances:
      zombie: 15
      ghost: 20
      vampire: 25
      snake_wizard: 25
      ogr: 15
    enemy_count: [6, 8]
    items_count: [8, 12]
    treasure: [300, 500]

  - range: [16, 21]
    enemy_chances:
      zombie: 5
      ghost: 20
      vampire: 30
      snake_wizard: 25
      ogr: 20
    enemy_count: [8, 10]
    items_count: [6, 10]
    treasure: [600, 900] 

elixir:
  max_health: [2, 5]
  strength: [2, 4]
  agility: [2, 5]
  name: ["Elixir of the Hollow Vein",
    "Draught of Bleeding Moonlight",
    "Phial of Liquid Silence",
    "Tonic of Shattered Mirrors",
    "Vial of Ghostly Whispers",
    "Potion of the Pale Flame",
    "Serum of Twisted Echoes",
    "Flask of the Hollowed Mind",
    "Broth of the Nameless Path"]
  duration: [4, 8]

scroll:
  max_health: [2, 5]
  strength: [2, 4]
  agility: [2, 5]
  name: ["Scroll of Whispering Shadows",
    "Pact of the Silent Blade",
    "Glyph of Blinking Death",
    "Tome of Forgotten Steps",
    "Scroll of Phantom Echoes",
    "Mandate of Silent Judas",
    "Scroll of Venomous Truths",
    "Charter of the Hollow Flame",
    "Parchment of Endless Whispers"]
  duration: [5, 9]

food:
  health: [3, 12]
  name: ["Ashen Biscuit of Suffering",
    "Ration of Forgotten Flesh",
    "Dried Eyes of the Blind Rat",
    "Cracked Husk of Old Corn",
    "Bread of the Hollow Man",
    "Meat Slab from the Pale Stag",
    "Lump of Spoiled Memory",
    "Blackened Root of Whispers",
    "Salted Dust of the Fallen"]

weapon:
  strength: [4, 18]
  name: ["Dagger of the Forgotten Shadow",
    "Bloodletter Shiv",
    "Wraithbone Shortsword",
    "Cursed Blade of Echoes",
    "Ruinseeker Dagger",
    "Ashen Pike",
    "Fang of the Betrayed",
    "Grimtooth Kris",
    "Veilbreaker Axe"]

enemy_agility:
  low: [1, 3]
  middle: [4, 6]
  high: [7, 9]
  very_high: [10, 12]
enemy_strength:
  low: [1, 3]
  middle: [3, 5]
  high: [6, 9]
  very_high: [10, 14]
enemy_animosity:
  low: [3, 5]
  middle: [6, 8]
  high: [9, 11]
  very_high: [12, 15]
enemy_health:
  low: [5, 8]
  middle: [9, 14]
  high: [15, 22]
  very_high: [23, 40]

enemies:
  zombie:
    enemy_agility: low
    enemy_strength: middle
    enemy_animosity: middle
    enemy_health: high
  ghost:
    enemy_agility: high
    enemy_strength: low
    enemy_animosity: low
    enemy_health: low
  vampire:
    enemy_agility: high
    enemy_strength: middle
    enemy_animosity: high
    enemy_health: high
  snake_wizard:
    enemy_agility: very_high
    enemy_strength: middle
    enemy_animosity: high
    enemy_health: middle
  ogr:
    enemy_agility: low
    enemy_strength: very_high
    enemy_animosity: middle
    enemy_health: very_high




